export const OBTENER_DATA ='OBTENER_DATA';
export const OBTENER_DATA_EXITO ='OBTENER_DATA_EXITO';
export const OBTENER_DATA_ERROR ='OBTENER_DATA_ERROR';

export const OBTENER_SEARCH_TERM = 'OBTENER_SEARCH_TERM';
export const FILTRAR_BUSQUEDA = 'FILTRAR_BUSQUEDA';
export const FILTRAR_BUSQUEDA_EXITO = 'FILTRAR_BUSQUEDA_EXITO';
export const FILTRAR_BUSQUEDA_ERROR = 'FILTRAR_BUSQUEDA_ERROR';

export const OBTENER_PERSONAJE = 'OBTENER_PERSONAJE';
export const OBTENER_COMIC_EXITO = 'OBTENER_COMIC_EXITO';
export const OBTENER_COMIC_ERROR = 'OBTENER_COMIC_ERROR';